//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /run/media/rd211/SHARED/find_my_lambda/LanguageEvaluators/C#/CSRunner/CSRunner/Parser/Antlr/Lambda.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="LambdaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface ILambdaListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LambdaParser.input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInput([NotNull] LambdaParser.InputContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LambdaParser.input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInput([NotNull] LambdaParser.InputContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LambdaParser.tuple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTuple([NotNull] LambdaParser.TupleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LambdaParser.tuple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTuple([NotNull] LambdaParser.TupleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LambdaParser.arr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArr([NotNull] LambdaParser.ArrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LambdaParser.arr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArr([NotNull] LambdaParser.ArrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LambdaParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] LambdaParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LambdaParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] LambdaParser.ValueContext context);
}
